# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uMPKFRhL1k2JAAhTfoI47bdg0GYXTMlz

Linear Regression-classification method(Supervised Learning)
Purpose:To predict data by given data
Method 1: Using pandas and Seaborn(St gr)
"""

import pandas as pd
ds=pd.read_csv("/content/nba.csv")
df=pd.DataFrame(ds)
d1=df.iloc[:,4:7]
d2=df.iloc[:,-1:]
print(type(d1))
l=[d1,d2]
#joining with column major
d3=pd.concat(l,axis=1,ignore_index=False)
d4=d3.dropna()
d4

d4.info()

import matplotlib.pyplot as plt
import seaborn as sn
l=[d4['Age']]
l2=[d4['Salary']]
plt.xlabel("AGE")
plt.ylabel("SALARY")
sn.regplot(x=l,y=l2)
plt.show()
plt.savefig("chart1.png")

"""Method 2: Using numpy and Scikit learn (St Mod)(unsupervised,supervised)ml algo's"""

import numpy as np
import matplotlib.pyplot as plt
x=np.array([d4['Age']])
y=np.array(d4['Salary'])

x=x.reshape(-1,1)
y=y.reshape(-1,1)
#print(x)
#print(y)

from sklearn.linear_model import LinearRegression
lr=LinearRegression()

lr.fit(x,y)

y_pred=lr.predict(x)
y_pred=y_pred.reshape(-1,1)
plt.xlabel("AGE")
plt.ylabel("SALARY")
plt.scatter(x,y,color="green",marker="o")
plt.plot(x,y_pred,color="red")
plt.show()

print(min(d4['Salary']))

plt.savefig("chart1.png")